### PR TITLE
Set up for NPM and Bower

### PR DESCRIPTION
**Pull request by camjc**
- Cleanup Readme.

### CODE REVIEW

**Comment by robmunro** [comment]
LGTM - what happened to Flow?

**Comment by antklim** [comment]
Looks awesome :cake: 
LGTM

**Comment by omgaz** [comment]
LGTM :fish_cake:

**Comment by omgaz** [comment]
Merging, Flow isn't used in anything yet so Cam said he'll add it back when it is. :ramen:

**Pull request merged**
