### PR TITLE
Update: Nicer line-height for Empty component with multiple lines

### PR DESCRIPTION
**Pull request by vinteo**
image

### CODE REVIEW

**Comment by omgaz** [comment]
LGTM :fish_cake:

**Comment by camjc** [comment]
Can we please make a `$line-height-etalon = 1.5` for reuse and make the `margin-top: $spacing-etalon /3`

**Comment by vinteo** [comment]
@omgaz @camjc merge?

**Comment by omgaz** [comment]
Merging :ramen:

**Pull request merged**
