### PR TITLE
Build: Update all tests to use enzyme

### PR DESCRIPTION
**Pull request by vinteo**

### CODE REVIEW

**Comment by camjc** [comment]
We're going to change back the `hasClass`s. LGTM after that.

**Comment by camjc** [comment]
LGTM!

**Comment by antklim** [comment]
Great enzym test :microscope: LGTM :100:

**Comment by omgaz** [comment]
LGTM

**Comment by vinteo** [comment]
@camjc @antklim @omgaz merge?

**Comment by camjc** [comment]
Merging!

**Pull request merged**
