### PR TITLE
New: Flexible wrapper and spacer

### PR DESCRIPTION
**Pull request by patrick-ivers**
I have decided to move the flexible-spacer functionality into Alexandria. I'll reopen the adslot-ui PR with these updates.

#### Changes
- Rename FlexSpacer to FlexibleSpacer to convey functionality rather than implementation
- Add .flexible-wrapper-inline styles to make FlexibleSpacer usable inline
- Refactor PageTitleComponent to use .flexible-* styles rather than floats
- Remove redundant .pagetitle-component-children styles
- Update PageTitleComponentTest.js
- Rename fontSize.scss and fontWeight.scss to font-size.scss and font-weight.scss for consistency

#### Trello
https://trello.com/c/OWT71p6Z/5420-adslot-ui-add-support-for-icons-in-buttons-also-update-adslot-ui-port-number-to-8001

#### Screenshots
screen shot 2016-06-21 at 4 49 40 pm
screen shot 2016-06-21 at 5 19 18 pm

### CODE REVIEW

**Comment by vinteo** [comment]
you need to run `npm run dist` or setup the git-hooks

**Comment by patrick-ivers** [comment]
@vinteo Thanks. Done.

**Comment by omgaz** [comment]
LGTM

**Comment by omgaz** [comment]
Merging 🍜

**Pull request merged**
